### PR TITLE
First gem-ing for Rails 3.0

### PR DESCRIPTION
**Pull request by gwarf**
Hi guys,
Here it is. :)
Please note that this is only working/"tested" with Rails 3.0.1 and it's not (yet) compatible with installation as a plugin... 
Also the licence files/gem specification and other things will have to be updated.
At least :)

Cheers,
Baptiste

### CODE REVIEW

**Comment by cingel** [comment]
Thanks Baptiste!

I merged it, tested, and only thing that doesn't work for me is controller generator.
rails generate miu_controller
I see that you used miucontroller (rails generate miucontroller), is there a reason you renamed the generator?

It will best I think to create new branch "rails2" that will have state before your fork and do all future development in master branch for rails3. Let me know what you think?

I added you to contributors list, is that ok?

Thanks once more
Vlado

**Comment by gwarf** [comment]
Hi Vlado,
In fact the miucontroller is "working": 
    baptiste@arakis % rails generate miucontroller 
      create  app/controller/mark_it_up_controller.rb
      create  app/views/mark_it_up/preview.html.erb
       route  match "mark_it_up/preview" => "mark_it_up#preview"
     \* Copying assets to /home/baptiste/dev/workspace-perso/mark_it_up_fake/public/mark_it_up
     \* Run 'script/generate miu_controller' to generate MarkItUpController and to be able to use default preview  parser

But the controller is created in the wrong dir (app/controller) ... I think I was a bit tired when I tested it ;) In fact an old apps/controller/mark_it_up_controller.rb was there... Sorry :)

No I had no good reason to rename the generator, it was even not "voluntary", I do agree that without a real good motivation it's better to stick to the existing interface/API.

I will commit some fixes for this two issues as soon as possible.

Concerning the branching model, it's as you want, we can do what you propose or switch to a more complex model like this one: http://nvie.com/posts/a-successful-git-branching-model/ .
But it's sure that the actual rails 2 plugin working stuff should still be easily accessible until it will be properly implemented in the gem version.

And thanks for the addition to the contributor list :)

Cheers,
Baptiste

**Comment by cingel** [comment]
I like the branching model you linked, great stuff, we can follow that.
I've added you as collaborator, so you can work in the future here so we can have one step less (pull request). Is that ok with you?

**Comment by gwarf** [comment]
OK :)

**Comment by cingel** [comment]
Welcome then :)

I created rails2 branch https://github.com/cingel/mark_it_up/tree/rails2
We can have this as plugin (no gem), leave it like it is and only do fixes in case of bug/problem (eventually some new feature if we can apply it fast).
I suggest we do all future development only for Rails 3 and we can use your branching model for it?

**Comment by gwarf** [comment]
Thanks for getting me in :)
Yep I think we could keep our master the stable branch, having a develop branch where changes from the different features branch are merged.
(Sometimes with small project or small changes I commit changes directly to the develop branch...)

Cheers,
Baptiste

**Pull request merged**
